name: Run markdown lint
on: 
  push:
    branches: main
jobs:
 Run_the_test:
  runs-on: ubuntu-latest
 
  steps: 
    - name: Run install
      run: |
        npm install remark-cli remark-preset-lint-consistent
        npx remark . --use remark-preset-lint-consistent --frail
